securityContext:
  privileged: true

image:
  pullPolicy: IfNotPresent

ipam:
  mode: kubernetes

operator:
  replicas: 1  

cluster:
  name: ${cluster}
  id: ${ordinal}

nodePort:
  enabled: true   

l2announcements: 
  enabled: true
  interface: eth0
   
k8sClientRateLimit:
  qps: 32
  burst: 68

externalIPs:
  enabled: true   

kubeProxyReplacement: true 

k8sServiceHost: localhost
k8sServicePort: 6443  





     
