securityContext:
  privileged: true

image:
  pullPolicy: IfNotPresent

ipam:
  mode: kubernetes

operator:
  replicas: 1
  prometheus:
    enabled: true    

cluster:
  name: ${cluster}
  id: ${ordinal}

nodePort:
  enabled: true

l2announcements: 
  enabled: true
  interface: eth0
   
k8sClientRateLimit:
  qps: 32
  burst: 68

externalIPs:
  enabled: true   

kubeProxyReplacement: true 

k8sServiceHost: localhost
k8sServicePort: 6443  
 

clustermesh:
  useAPIServer: true
  config:
    enabled: true
    clusters: 
    - name: cluster1
      port: 2379
      addresses: cluster1.mesh.cilium.io
      ips: 
      - ${cluster1_ip}
    - name: cluster2
      port: 2379
      addresses: cluster2.mesh.cilium.io
      ips: 
      - ${cluster2_ip}
    - name: cluster3
      port: 2379
      addresses: cluster3.mesh.cilium.io
      ips: 
      - ${cluster3_ip}   
  apiserver:
    tls:
      auto:
        certManagerIssuerRef:
          name: in-cluster-issuer
          kind: ClusterIssuer
          group: cert-manager.io        
        method: certmanager
    service:
      type: LoadBalancer
      loadBalancerIP: ${apiserver_ip}

gatewayAPI:
  enabled: false

ingressController:
  enabled: false
  default: true

prometheus:
  enabled: true 

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
  tls:
    auto:
      method: certmanager
      certManagerIssuerRef:
        name: in-cluster-issuer
        kind: ClusterIssuer
        group: cert-manager.io         


     
