apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: sample.shared.example.com
spec:
  insecureSkipTLSVerify: true
  group: shared.example.com
  version: v1
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: kcp
    namespace: h2
    port: 6443
