apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: sample.shared.example.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: shared.example.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      subresources:
        # status enables the status subresource.
        status: {}      
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                foo:
                  type: string
            status:
              type: object
              properties:
                status:
                  type: string
                clusterStatuses:
                  type: array
                  x-kubernetes-list-map-keys:
                  - cluster
                  x-kubernetes-list-type: map
                  properties: 
                    cluster:
                      type: string
                    status:
                      type: string                                      
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: samples
    # singular name to be used as an alias on the CLI and for display
    singular: sample
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Sample